language: php
php:
- 7.0
- 5.6
script:
- php -l *.php
branches:
  only:
  - "/\\d\\.\\d\\.\\d/"
deploy:
  provider: script
  script: deploy/deploy.sh
  on:
    tags: true
env:
  global:
  - SVN_REPOSITORY=https://plugins.svn.wordpress.org/wp-simple-mail-sender/
  - secure: cA7etr+/EU5BCcC+zkdrII2vn7hSQblSHGqFzgmsh3RhGke1bstRG5xnE/LILXKNfnXnGTlPEABHjw/pfW0UK9yqMOAX9FpVg6x+MSe2jvV4YhI7Ul3dx2JbUUhG6Dw0Vw9nhpIdwS1CkhqT3Z4fYfODqCnqp/Sas21F969Xg9Q=
  - secure: SbGr8zYe8trDcNylwSL5AUHi5CoIfjJpb34Q82n5mN1P9uQ4Mn7BqFUfJhJxZXodNLgPUkqtku3k1GnbA698HfGqKX8h9Qh+v4l0AnunSuTJRyGId4mvWpg9fP0GDehGvHM6+gjmFonyGeydazbtz21/HVU/fSENv25FodOKI1U=
